[versions]
y9-plugin = "9.7.0-08"
y9-digitalbase = "9.7.0-SNAPSHOT"

flowable-spring-boot = "7.1.0"

# database
com-oracle-database-jdbc-ojdbc11 = "21.9.0.0"
kingbase-hibernate-dialect = "5.4.6.Finaldialect"
kingbase-hibernate-jpa-api = "2.1.0.Final"
kingbase-kingbase8 = "8.6.1"

cn-songxinqiang-com-baidu-ueditor = "1.1.2-offical"
cn-wps-yun-graph-java-client = "1.0.11"
com-alibaba-fastjson = "2.0.53"
com-belerweb-pinyin4j = "2.5.1"
com-deepoove-poi-tl = "1.12.1"
com-github-alexheretic-fluent = "2.0"
com-jxl-jxl = "2.6"
net-coobird-thumbnailator = "0.4.20"
org-jodd-jodd-mail = "7.1.0"

# for jodconverter
antlr-antlr = "2.7.7"
cn-hutool-hutool-http = "5.8.23"
com-aspose-aspose-cad = "23.3"
com-googlecode-juniversalchardet-juniversalchardet = "1.0.3"
com-googlecode-concurrentlinkedhashmap-concurrentlinkedhashmap-lru = "1.4.2"
com-github-jai-imageio = "1.4.0"
com-github-junrar-junrar = "7.5.4"
com-itextpdf-itextpdf = "5.5.13.3"
com-thoughtworks-xstream-xstream = "1.4.20"
commons-cli-commons-cli = "1.2"
commons-net-commons-net = "3.11.1"
fr-opensagres-xdocreport = "1.0.6"
io-mola-galimatias-galimatias = "0.2.1"
javax-media-jai-core = "1.1.3"
net-sf-sevenzipjbinding = "16.02-2.01"
net-sourceforge-jchardet-jchardet = "1.0"
org-jodconverter-jodconverter-local = "4.4.6"
org-apache-poi-poi = "5.2.3"
org-apache-poi-poi-ooxml-schemas = "4.1.2"
org-apache-pdfbox-jbig2-imageio = "3.0.4"
org-apache-pdfbox-pdfbox = "2.0.27"
org-bytedeco-javacv = "1.5.2"
org-bytedeco-ffmpeg = "4.2.1-1.5.2"
org-bytedeco-javacpp = "1.5.2"
org-bytedeco-openblas = "0.3.28-1.5.11"
org-bytedeco-opencv = "4.1.2-1.5.2"
org-redisson-redisson = "3.2.0"
org-rocksdb-rocksdbjni = "5.17.2"
org-bouncycastle-bcprov-jdk15on = "1.70"


[libraries]
y9-digitalbase-bom = { module = "net.risesoft:y9-digitalbase-bom", version.ref = "y9-digitalbase" }
y9-digitalbase-dependencies = { module = "net.risesoft:y9-digitalbase-dependencies", version.ref = "y9-digitalbase" }

flowable-spring-boot-starter-process = { module = "org.flowable:flowable-spring-boot-starter-process", version.ref = "flowable-spring-boot" }

# database
com-oracle-database-jdbc-ojdbc11 = { module = "com.oracle.database.jdbc:ojdbc11", version.ref = "com-oracle-database-jdbc-ojdbc11" }
kingbase-hibernate-dialect = { module = "cn.com.kingbase:hibernate-dialect", version.ref = "kingbase-hibernate-dialect" }
kingbase-hibernate-jpa-api = { module = "cn.com.kingbase:hibernate-jpa-api", version.ref = "kingbase-hibernate-jpa-api" }
kingbase-kingbase8 = { module = "cn.com.kingbase:kingbase8", version.ref = "kingbase-kingbase8" }

com-baidu-ueditor = { module = "cn.songxinqiang:com.baidu.ueditor", version.ref = "cn-songxinqiang-com-baidu-ueditor" }
graph-java-client = { module = "cn.wps.yun:graph-java-client", version.ref = "cn-wps-yun-graph-java-client" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "com-alibaba-fastjson" }
fluent = { module = "com.github.alexheretic:fluent", version.ref = "com-github-alexheretic-fluent" }
jxl = { module = "com.jxl:jxl", version.ref = "com-jxl-jxl" }
jodd-mail = { module = "org.jodd:jodd-mail", version.ref = "org-jodd-jodd-mail" }
pinyin4j = { module = "com.belerweb:pinyin4j", version.ref = "com-belerweb-pinyin4j" }
poi-tl = { module = "com.deepoove:poi-tl", version.ref = "com-deepoove-poi-tl" }
thumbnailator = { module = "net.coobird:thumbnailator", version.ref = "net-coobird-thumbnailator" }


# jodconverter
hutool-http = { module = "cn.hutool:hutool-http", version.ref = "cn-hutool-hutool-http" }
fr-opensagres-xdocreport-document = { module = "fr.opensagres.xdocreport:fr.opensagres.xdocreport.document", version.ref = "fr-opensagres-xdocreport" }
jodconverter-local = { module = "org.jodconverter:jodconverter-local", version.ref = "org-jodconverter-jodconverter-local" }
org-apache-poi-xwpf-converter-core = { module = "fr.opensagres.xdocreport:org.apache.poi.xwpf.converter.core", version.ref = "fr-opensagres-xdocreport" }
org-apache-poi-xwpf-converter-xhtml = { module = "fr.opensagres.xdocreport:org.apache.poi.xwpf.converter.xhtml", version.ref = "fr-opensagres-xdocreport" }
poi = { module = "org.apache.poi:poi", version.ref = "org-apache-poi-poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "org-apache-poi-poi" }
poi-ooxml-schemas = { module = "org.apache.poi:poi-ooxml-schemas", version.ref = "org-apache-poi-poi-ooxml-schemas" }
poi-scratchpad = { module = "org.apache.poi:poi-scratchpad", version.ref = "org-apache-poi-poi" }
sevenzipjbinding = { module = "net.sf.sevenzipjbinding:sevenzipjbinding", version.ref = "net-sf-sevenzipjbinding" }
sevenzipjbinding-all-platforms = { module = "net.sf.sevenzipjbinding:sevenzipjbinding-all-platforms", version.ref = "net-sf-sevenzipjbinding" }
redisson = { module = "org.redisson:redisson", version.ref = "org-redisson-redisson" }

## 以下是：编码检测-JUniversalCharDet
juniversalchardet = { module = "com.googlecode.juniversalchardet:juniversalchardet", version.ref = "com-googlecode-juniversalchardet-juniversalchardet" }

## 以下是：解压(rar)
antlr = { module = "antlr:antlr", version.ref = "antlr-antlr" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli-commons-cli" }
jchardet = { module = "net.sourceforge.jchardet:jchardet", version.ref = "net-sourceforge-jchardet-jchardet" }
junrar = { module = "com.github.junrar:junrar", version.ref = "com-github-junrar-junrar" }

## 以下是：PDF
aspose-cad = { module = "com.aspose:aspose-cad", version.ref = "com-aspose-aspose-cad" }
commons-net = { module = "commons-net:commons-net", version.ref = "commons-net-commons-net" }
concurrentlinkedhashmap-lru = { module = "com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru", version.ref = "com-googlecode-concurrentlinkedhashmap-concurrentlinkedhashmap-lru" }
jai-imageio-core = { module = "com.github.jai-imageio:jai-imageio-core", version.ref = "com-github-jai-imageio" }
jai-imageio-jpeg2000 = { module = "com.github.jai-imageio:jai-imageio-jpeg2000", version.ref = "com-github-jai-imageio" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "org-apache-pdfbox-pdfbox" }
pdfbox-jbig2-imageio = { module = "org.apache.pdfbox:jbig2-imageio", version.ref = "org-apache-pdfbox-jbig2-imageio" }
pdfbox-tools = { module = "org.apache.pdfbox:pdfbox-tools", version.ref = "org-apache-pdfbox-pdfbox" }
rocksdbjni = { module = "org.rocksdb:rocksdbjni", version.ref = "org-rocksdb-rocksdbjni" }
xstream = { module = "com.thoughtworks.xstream:xstream", version.ref = "com-thoughtworks-xstream-xstream" }

## 以下是密钥算法
bcprov-jdk15on = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "org-bouncycastle-bcprov-jdk15on" }

## 以下是：url 规范化
galimatias = { module = "io.mola.galimatias:galimatias", version.ref = "io-mola-galimatias-galimatias" }

## 以下是：bytedeco 基于opencv ffmpeg封装的javacv，用于视频处理
itextpdf = { module = "com.itextpdf:itextpdf", version.ref = "com-itextpdf-itextpdf" }
jai-codec = { module = "javax.media:jai_codec", version.ref = "javax-media-jai-core" }
jai-core = { module = "javax.media:jai-core", version.ref = "javax-media-jai-core" }
org-bytedeco-ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "org-bytedeco-ffmpeg" }
org-bytedeco-javacpp = { module = "org.bytedeco:javacpp", version.ref = "org-bytedeco-javacpp" }
org-bytedeco-javacv = { module = "org.bytedeco:javacv", version.ref = "org-bytedeco-javacv" }
org-bytedeco-openblas = { module = "org.bytedeco:openblas", version.ref = "org-bytedeco-openblas" }
org-bytedeco-opencv = { module = "org.bytedeco:opencv", version.ref = "org-bytedeco-opencv" }
# jodconverter end

[plugins]
y9-aspectj = { id = "net.risesoft.y9.aspectj", version.ref = "y9-plugin" }
y9-docker = { id = "net.risesoft.y9.docker", version.ref = "y9-plugin" }
y9-conventions-java = { id = "net.risesoft.y9.conventions-java", version.ref = "y9-plugin" }
y9-conventions-war = { id = "net.risesoft.y9.conventions-war", version.ref = "y9-plugin" }
y9-java-publish = { id = "net.risesoft.y9.java-publish", version.ref = "y9-plugin" }
y9-java-publish-central = { id = "net.risesoft.y9.java-publish-central", version.ref = "y9-plugin" }
y9-javaPlatform-publish = { id = "net.risesoft.y9.javaPlatform-publish", version.ref = "y9-plugin" }
y9-javaPlatform-publish-central = { id = "net.risesoft.y9.javaPlatform-publish-central", version.ref = "y9-plugin" }
y9-lombok = { id = "net.risesoft.y9.lombok", version.ref = "y9-plugin" }
y9-repository = { id = "net.risesoft.y9.repository", version.ref = "y9-plugin" }
y9-smart-doc = { id = "net.risesoft.y9.smart-doc", version.ref = "y9-plugin" }