management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
        context-path: /flowableUI
        register-default-servlet: true
spring:
    application:
        name: flowableUI
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    cloud:
        nacos:
            server-addr: https://test.youshengyun.com:443
            username: nacos
            password: ${NACOS_PASSWORD:111111}
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
            discovery:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
    config:
        import:
            - optional:nacos:flowableUI.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    cache:
        redis:
            time-to-live: PT2H
        type: redis
    data:
        jpa:
            repositories:
                bootstrap-mode: default
                enabled: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    mergeSql: true
                    slow-sql-millis: 3000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                enabled: false
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
                reset-enable: false
                allow: 127.0.0.1
            web-stat-filter:
                enabled: false
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
            y9-public:
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                #password: '111111'
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false
                username: root
                password: '111111'
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jpa:
        generate-ddl: true
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: none
                jdbc:
                    batch_size: 100
                show_sql: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9flowableUI-server
    main:
        allow-bean-definition-overriding: false
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    redis:
        database: 9
        host: 192.168.3.31
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        password: Y9i-83204585
        port: 6379
        ssl: false
        timeout: 10000
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 1000MB
    web:
        resources:
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:///d:/y9config/
y9:
    systemName: flowableUI
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x
    app:
        flowable:
            systemCnName: 办件3.0
            systemName: flowableUI
    service:
        itemAdmin:
            directUrl: http://localhost:7057
        processAdmin:
            directUrl: http://localhost:7056
        org:
            directUrl: http://localhost:7055
        todo:
            directUrl: http://localhost:7055
    common:
        cacheEnabled: true
        kafkaEnabled: true
        flowableBaseUrl: http://localhost:7058/flowableUI
        itemAdminBaseUrl: http://localhost:7057/itemAdmin
        orgBaseUrl: http://localhost:7055/platform
        processAdminBaseUrl: http://localhost:7056/processAdmin
        todoBaseUrl: https://test.youshengyun.com/todo
        todoTaskUrlPrefix: https://test.youshengyun.com/flowableUI/todoIndex
        jodconverterBaseUrl: http://localhost:7055/jodconverter/onlinePreview?url=
        logBaseUrl: http://localhost:7056/log
        userOnlineBaseUrl: http://localhost:7056/userOnline
    feature:
        apisix:
            enabled: false
            adminAddress: http://localhost:8888/apisix/admin/
            adminKey: edd1c9f034335f136f87ad84b625c8f1
            upstreamType: roundrobin   #负载均衡算法，1、roundrobin:轮训 ; 2、chash:一致性哈希; 3、ewma:指数加权移动平均法; 4、least_conn:最小连接数
            #etcdAddress: http://localhost:2379  #有多个时逗号分隔
            apiBasePackages: net.risesoft.controller.mobile #有多个时逗号分隔
        file:
            base64FileName: false
            encryptionFileContent: false
            #privateKey:
            #publicKey:
            rest:
                fileManagerUrl: http://test-api.youshengyun.com/fileManager
            ftp:
                host: nexus-internal.youshengyun.com
                port: 21
                username: y9admin
                password: '83204585'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        multi-tenant:
            # kafka, db
            event-source: kafka
        log:
            enabled: true
            # kafka, api
            logSaveTarget: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            csrf:
                accepted-referer:
                    - localhost
                    - 127.0.0.1
                    - youshengyun.com
                    - 192.168.3.120
            cors:
                allowCredentials: true
                allowed-headers: '*'
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7070
                    - http://localhost:7055
                    - http://localhost:7056
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:8082
                    - http://localhost:8083
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
                    - http://127.0.0.1:7070
                    - http://localhost:17061
                    - http://127.0.0.1:17061
                    - http://192.168.3.120:8080
            xss:
                ignoreParam:
                    - jsonData
                    - formJson
                    - fieldJson
                    - printUrl
                    - formdata
                    - formJsonData
                    - documentTitle
                    - title
                    - searchMapStr
        oauth2:
            resource:
                enabled: true
                saveOnlineMessage: false
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /vue/*
                opaque:
                    client-id: clientid
                    client-secret: secret
                    introspection-uri: http://localhost:7055/sso/oauth2.0/introspect
                    profile-uri: http://localhost:7055/sso/oauth2.0/profile
